name: bevnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=2.111=mkl
  - blas-devel=3.9.0=11_win64_mkl
  - brotlipy=0.7.0=py38h294d835_1003
  - ca-certificates=2021.10.8=h5b45459_0
  - certifi=2021.10.8=py38haa244fe_0
  - cffi=1.15.0=py38hd8c33c5_0
  - cryptography=36.0.2=py38hb7941b4_0
  - cudatoolkit=11.1.1=heb2d755_9
  - freetype=2.10.4=h546665d_1
  - intel-openmp=2021.3.0=h57928b3_3372
  - jbig=2.1=h8d14728_2003
  - jpeg=9b=hb83a4c4_2
  - lerc=3.0=h0e60522_0
  - libblas=3.9.0=11_win64_mkl
  - libcblas=3.9.0=11_win64_mkl
  - libdeflate=1.10=h8ffe710_0
  - liblapack=3.9.0=11_win64_mkl
  - liblapacke=3.9.0=11_win64_mkl
  - libpng=1.6.37=h1d00b33_2
  - libtiff=4.2.0=hd0e1b90_0
  - libuv=1.42.0=h8ffe710_0
  - libwebp=1.2.2=h57928b3_0
  - libwebp-base=1.2.2=h8ffe710_1
  - libxcb=1.13=hcd874cb_1004
  - libzlib=1.2.11=h8ffe710_1013
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mkl=2021.3.0=hb70f87d_564
  - mkl-devel=2021.3.0=h57928b3_565
  - mkl-include=2021.3.0=hb70f87d_564
  - msys2-conda-epoch=20160418=1
  - ninja=1.10.2=h2d74725_1
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb211442_1
  - openssl=1.1.1l=h8ffe710_0
  - pillow=8.3.1=py38h4fa10fc_0
  - pip=21.0.1=py38haa95532_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py38haa244fe_4
  - python=3.8.11=h6244533_1
  - python_abi=3.8=2_cp38
  - pytorch=1.9.1=py3.8_cuda11.1_cudnn8_0
  - pytorch-mutex=1.0=cpu
  - pywin32=228=py38hbaba5e8_1
  - setuptools=58.0.4=py38haa95532_0
  - sqlite=3.36.0=h2bbff1b_0
  - tbb=2021.3.0=h2d74725_0
  - tk=8.6.11=h8ffe710_1
  - torchaudio=0.9.1=py38
  - torchvision=0.10.1=py38_cu111
  - typing_extensions=3.10.0.2=pyha770c72_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.0=pyhd3eb1b0_1
  - win_inet_pton=1.1.0=py38haa244fe_3
  - wincertstore=0.2=py38haa95532_2
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.5=h62dcd97_1
  - zlib=1.2.11=h8ffe710_1013
  - zstd=1.4.9=h6255e5f_0
  - pip:
    - absl-py==0.14.1
    - ansicon==1.89.0
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - black==21.4b2
    - blessed==1.19.0
    - cachetools==4.2.4
    - charset-normalizer==2.0.7
    - click==8.0.3
    - cloudpickle==2.0.0
    - colorama==0.4.4
    - colorlog==6.5.0
    - cycler==0.10.0
    - cython==0.29.24
    - fonttools==4.31.2
    - future==0.18.2
    - fvcore==0.1.5.post20210924
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.41.0
    - h5py==3.4.0
    - hydra-core==1.1.1
    - idna==3.2
    - imageio==2.9.0
    - importlib-metadata==4.11.3
    - importlib-resources==5.2.2
    - iopath==0.1.9
    - jinxed==1.1.0
    - kiwisolver==1.3.2
    - markdown==3.3.4
    - matplotlib==3.4.3
    - mypy-extensions==0.4.3
    - networkx==2.6.3
    - numpy==1.22.3
    - nvidia-ml-py==11.470.66
    - oauthlib==3.1.1
    - omegaconf==2.1.1
    - opencv-python==4.5.3.56
    - packaging==21.3
    - pandas==1.3.3
    - pathspec==0.9.0
    - portalocker==2.3.2
    - protobuf==3.18.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.2
    - pydot==1.4.2
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - regex==2021.10.8
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - ruamel-yaml==0.17.16
    - ruamel-yaml-clib==0.2.6
    - scikit-image==0.18.3
    - scipy==1.7.1
    - seaborn==0.11.2
    - six==1.16.0
    - snakeviz==2.1.0
    - tabulate==0.8.9
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.4
    - termcolor==1.1.0
    - tifffile==2021.10.10
    - toml==0.10.2
    - torch-tb-profiler==0.2.1
    - tornado==6.1
    - tqdm==4.62.3
    - urllib3==1.26.7
    - wcwidth==0.2.5
    - werkzeug==2.0.2
    - yacs==0.1.8
    - zipp==3.6.0
